//@version=5
strategy(title="@課程範例－RSI指標交易模組（超買超賣逆勢進場、順勢進場）｜量化通", shorttitle="RSI範例策略｜量化通", //圖表上顯示的短名稱
overlay = false, //true疊圖，false下方單獨視窗 format=format.price, //format.price輸出格式為價格 precision=2, //顯示小數點後兩位
default_qty_type=strategy.cash, initial_capital=10000, //初始本金1萬 default_qty_value=10000, commission_value=0.04 ) //每次進場1萬，手續費單邊萬分之
4

//start前置設定

strategy.cancel_all() //每次收K都清空委託單
//常用函數
MP = strategy.opentrades.size(strategy.opentrades -1)>0?1:strategy.opentrades.size(strategy.opentrades - 1)<0?-1:0
//end前置設定


//RSI指標計算
rsiLen = input.int(14, minval=1, maxval=1000, step=2, title="RSI長度", group="RSI參數設定")
rsiUpper = input.int(70, minval=0, maxval=100, step=5, title="RSI上界", group="RSI參數設定")
rsiLower = input.int(30, minval=0, maxval=100, step=5, title="RSI下界", group="RSI參數設定")
rsi = ta.rsi(close,rsiLen)
type = input.string("超買超賣逆勢進場", options = ["超買超賣逆勢進場","順勢進場"])

//進場條件
MaxUseBars = 1+math.max(rsiLen,1)//每個策略要重新設定 var LongEntry = false
var ShortEntry = false

if type=="超買超賣逆勢進場"
LongEntry := bar_index>MaxUseBars and MP<=0 and ta.crossover(rsi,rsiLower)

ShortEntry := bar_index>MaxUseBars and MP>=0 and ta.crossunder(rsi,rsiUpper)
else if type=="順勢進場"
LongEntry := bar_index>MaxUseBars and MP<=0 and ta.crossover(rsi,rsiUpper)
ShortEntry := bar_index>MaxUseBars and MP>=0 and ta.crossunder(rsi,rsiLower)

//多單委託
if LongEntry
strategy.entry("LE", strategy.long) //多單進場

//空單委託
if ShortEntry
strategy.entry("SE", strategy.short) //空單進場

//上底色，持有多單底色綠色，持有空單底色紅色
colorBG = strategy.opentrades.size(strategy.opentrades-1)>0 ? color.new(color.green,80) :
strategy.opentrades.size(strategy.opentrades-1)<0 ? color.new(color.red,80)
:
color.new(color.gray,100)
bgcolor(colorBG, force_overlay=true)

//定義RSI線條顏色
rsiColor = rsi>=rsiUpper ? color.red :
rsi<=rsiLower ? color.green : color.blue
//繪圖
plot(rsi, "RSI", color=rsiColor, linewidth=2)
rsiUpperBand = hline(rsiUpper, "RSI上界", color=color.gray)
rsiLowerBand = hline(rsiLower, "RSI下界", color=color.gray)
rsi100Band = hline(100, "RSI_100", color=color.gray,linestyle=hline.style_solid)
rsi50Band = hline(50, "RSI中界", color=color.new(color.gray, 50))
rsi0Band = hline(0, "RSI_0", color=color.gray,linestyle=hline.style_solid)
fill(rsiUpperBand, rsi100Band, color=color.new(color.red,90), title="RSI上界 ")
fill(rsi0Band, rsiLowerBand, color=color.new(color.green,90), title="RSI下界 ")


