//@version=5
strategy(title="@課程範例－KD指標交易模組（低檔金叉、高檔死叉）｜量化通", shorttitle="KD範例策略｜量化通", //圖表上顯示的短名稱
overlay = false, //true疊圖，false下方單獨視窗 format=format.price, //format.price輸出格式為價格 precision=2, //顯示小數點後兩位
default_qty_type=strategy.cash, initial_capital=10000, //初始本金1萬 default_qty_value=10000, commission_value=0.04 ) //每次進場1萬，手續費單邊萬分之
4

//start前置設定

strategy.cancel_all() //每次收K都清空委託單
//常用函數
MP = strategy.opentrades.size(strategy.opentrades -1)>0?1:strategy.opentrades.size(strategy.opentrades - 1)<0?-1:0
//end前置設定


//KD指標計算
Len = input.int(9, maxval=1000 , minval=1 , step=1 , title="快線K", group="KD
參數設定")
DLen = input.int(3, maxval=1000 , minval=1 , step=1 , title="慢線D", group="KD參數設定")
kdUpper = input.int(80, maxval=100 , minval=0 , step=1 , title="超買區", group="KD參數設定")
kdLower = input.int(20, maxval=100 , minval=0 , step=1 , title="超賣區", group="KD參數設定")
Fast = ta.stoch(close, high, low, Len)
K = ta.sma(Fast, DLen)
D = ta.sma(K, DLen)

//進場條件
MaxUseBars = 1+math.max(Len,DLen,1)//每個策略要重新設定
LongEntry = bar_index>MaxUseBars and MP<=0 and ta.crossover(K,D) and K<kdLower and D<kdLower
ShortEntry = bar_index>MaxUseBars and MP>=0 and ta.crossunder(K,D) and K>kdUpper and D>kdUpper


//空單委託
if ShortEntry
strategy.entry("SE", strategy.short) //空單進場

//上底色，持有多單底色綠色，持有空單底色紅色
colorBG = strategy.opentrades.size(strategy.opentrades-1)>0 ? color.new(color.green,80) :
strategy.opentrades.size(strategy.opentrades-1)<0 ? color.new(color.red,80)
:
color.new(color.gray,100)
bgcolor(colorBG, force_overlay=true)

//繪圖
plot(K, color = color.blue, title = "K")
plot(D, color = color.red, title = "D")
kdUpperBand = hline(kdUpper, "KD上界", color=color.gray)
kdLowerBand = hline(kdLower, "KD下界", color=color.gray)
kd100Band = hline(100, "KD_100", color=color.gray,linestyle=hline.style_solid)
kd50Band = hline(50, color = color.black, linestyle = hline.style_dashed)
kd0Band = hline(0, "KD_0", color=color.gray,linestyle=hline.style_solid)
fill(kdUpperBand, kd100Band, color=color.new(color.red,90), title="KD上界")
fill(kd0Band, kdLowerBand, color=color.new(color.green,90), title="KD下界")


