//@version=5
strategy(title="@課程範例－MACD指標交易模組（多空翻轉進場、柱狀轉弱出場）｜量化通", shorttitle="MACD範例策略｜量化通", //圖表上顯示的短名稱
overlay = false, //true疊圖，false下方單獨視窗 format=format.price, //format.price輸出格式為價格 precision=2, //顯示小數點後兩位
default_qty_type=strategy.cash, initial_capital=10000, //初始本金1萬 default_qty_value=10000, commission_value=0.04 ) //每次進場1萬，手續費單邊萬分之
4

//start前置設定

strategy.cancel_all() //每次收K都清空委託單
//常用函數
MP = strategy.opentrades.size(strategy.opentrades -1)>0?1:strategy.opentrades.size(strategy.opentrades - 1)<0?-1:0
//end前置設定


//MACD指標計算
fastLen = input.int(12, minval=1, maxval=100, step=3, title="MACD快線", group="參數設定")
slowLen = input.int(26, minval=1, maxval=200, step=5, title="MACD慢線", group="參數設定")
signalLen = input.int(9, minval=1, maxval=100, step=5, title="信號平滑長度", group="參數設定")
[macdLine, signalLine, histLine] = ta.macd(close, fastLen, slowLen, signalLen)

//進場條件
MaxUseBars = 1+math.max(fastLen, slowLen, signalLen,1)//每個策略要重新設定 LongEntry = bar_index>MaxUseBars and MP<=0 and ta.crossover(histLine,0)
ShortEntry = bar_index>MaxUseBars and MP>=0 and ta.crossunder(histLine,0)
LongExit = MP>0 and math.min(histLine,histLine[1],histLine[2],histLine[3])>0 and histLine[3]-histLine>5 //此處為正確的，影片中的程式碼有誤
ShortExit = MP<0 and math.max(histLine,histLine[1],histLine[2],histLine[3])<0 and histLine-histLine[3]>5

if LongExit
strategy.close("LE", "LX")
//空單委託
if ShortEntry
strategy.entry("SE", strategy.short) //空單進場 if ShortExit
strategy.close("SE", "SX")

//上底色，持有多單底色綠色，持有空單底色紅色
colorBG = strategy.opentrades.size(strategy.opentrades-1)>0 ? color.new(color.green,80) :
strategy.opentrades.size(strategy.opentrades-1)<0 ? color.new(color.red,80)
:
color.new(color.gray,100)
bgcolor(colorBG, force_overlay=true)
//繪圖
hline(0, "Zero Line", color = color.new(color.silver, 50))
plot(histLine, title = "Histogram", style = plot.style_columns,
color = (histLine >= 0 ? (histLine[1] < histLine ? color.teal : color.green)
:
(histLine[1] < histLine ? color.fuchsia : color.red)))
plot(macdLine, title = "MACD",    color = color.blue)
plot(signalLine, title = "Signal", color = color.orange)


