//@version=5
strategy(title="@課程範例－均線交易模組（金叉死叉、多頭排列、空頭排列）｜量化通", shorttitle="均線範例策略｜量化通", //圖表上顯示的短名稱
overlay = true, //true疊圖，false下方單獨視窗 format=format.price, //format.price輸出格式為價格 precision=2, //顯示小數點後兩位
default_qty_type=strategy.cash, initial_capital=10000, //初始本金1萬 default_qty_value=10000, commission_value=0.04 ) //每次進場1萬，手續費單邊萬分之
4

//start前置設定

strategy.cancel_all() //每次收K都清空委託單
//常用函數
MP = strategy.opentrades.size(strategy.opentrades -1)>0?1:strategy.opentrades.size(strategy.opentrades - 1)<0?-1:0
//end前置設定


//均線指標計算
SmallLen = input.int(25, maxval=1000 , minval=1 , step=1 , title="短均線參數 ")
MidLen = input.int(50, maxval=1000 , minval=1 , step=1 , title="中均線參數")
BigLen = input.int(100, maxval=1000 , minval=1 , step=1 , title="長均線參數")
type = input.string("金叉死叉", options = ["金叉死叉","多頭/空頭排列"])

SmallMA = ta.sma(close, SmallLen)
MidMA = ta.sma(close, MidLen)
BigMA = ta.sma(close, BigLen)

//進場條件
MaxUseBars = 1+math.max(SmallLen,MidLen,BigLen,1)//每個策略要重新設定 var LongEntry = false
var ShortEntry = false

if type=="金叉死叉"
LongEntry := bar_index>MaxUseBars and MP<=0 and ta.crossover(SmallMA,MidMA)

ta.crossunder(SmallMA,MidMA)
else if type=="多頭/空頭排列"
LongEntry := bar_index>MaxUseBars and MP<=0 and SmallMA>MidMA and MidMA>BigMA
ShortEntry := bar_index>MaxUseBars and MP>=0 and SmallMA<MidMA and MidMA<BigMA

//多單委託
if LongEntry
strategy.entry("LE", strategy.long) //多單進場

//空單委託
if ShortEntry
strategy.entry("SE", strategy.short) //空單進場

//上底色，持有多單底色綠色，持有空單底色紅色
colorBG = strategy.opentrades.size(strategy.opentrades-1)>0 ? color.new(color.green,80) :
strategy.opentrades.size(strategy.opentrades-1)<0 ? color.new(color.red,80)
:
color.new(color.gray,100)
bgcolor(colorBG, force_overlay=true)

//繪圖
plot(SmallMA, color=color.blue, title="短均線")
plot(MidMA, color=color.purple, title="中均線")
plot(BigMA, color=color.orange, title="長均線")


