//@version=5
strategy(title="@課程範例－ATR指標交易模組（波動大、波動瞬間放大）｜量化通", shorttitle="ATR範例策略｜量化通", //圖表上顯示的短名稱
overlay = false, //true疊圖，false下方單獨視窗 format=format.price, //format.price輸出格式為價格 precision=2, //顯示小數點後兩位
default_qty_type=strategy.cash, initial_capital=10000, //初始本金1萬 default_qty_value=10000, commission_value=0.04 ) //每次進場1萬，手續費單邊萬分之
4

//start前置設定

strategy.cancel_all() //每次收K都清空委託單
//常用函數
MP = strategy.opentrades.size(strategy.opentrades -1)>0?1:strategy.opentrades.size(strategy.opentrades - 1)<0?-1:0
//end前置設定


//ATR指標計算
Len = input.int(20, minval=1, title="長度", group="ATR參數設定")
mult = input.float(1.5, minval=0.1, title="ATR倍數", group="ATR參數設定")
Bigmult = input.float(3.0, minval=0.1, title="瞬間ATR倍數", group="ATR參數設定 ")
type = input.string("波動大", options = ["波動大","波動瞬間放大"])
atr = ta.atr(Len)
ma = ta.sma(close, Len)

//進場條件
MaxUseBars = 1+math.max(Len,1)//每個策略要重新設定 var LongEntry = false
var ShortEntry = false

if type=="波動大"
LongEntry := bar_index>MaxUseBars and MP<=0 and close>close[1]+atr*mult and close>ma
ShortEntry := bar_index>MaxUseBars and MP>=0 and close<close[1]-atr*mult and close<ma

close>close[1]+atr*Bigmult
ShortEntry := bar_index>MaxUseBars and MP>=0 and close<close[1]-atr*Bigmult

//多單委託
if LongEntry
strategy.entry("LE", strategy.long) //多單進場

//空單委託
if ShortEntry
strategy.entry("SE", strategy.short) //空單進場

//上底色，持有多單底色綠色，持有空單底色紅色
colorBG = strategy.opentrades.size(strategy.opentrades-1)>0 ? color.new(color.green,80) :
strategy.opentrades.size(strategy.opentrades-1)<0 ? color.new(color.red,80)
:
color.new(color.gray,100)
bgcolor(colorBG, force_overlay=true)

//繪圖
plot(atr, color=color.gray, title="ATR", style = plot.style_histogram)
plot(ma, "均線", force_overlay=true)


