//@version=5
strategy(title="@課程範例－單根K棒反轉交易模組（大周期的AV轉）｜量化通", shorttitle="單根反轉範例策略｜量化通", //圖表上顯示的短名稱
overlay = true, //true疊圖，false下方單獨視窗 format=format.price, //format.price輸出格式為價格 precision=2, //顯示小數點後兩位
default_qty_type=strategy.cash, initial_capital=10000, //初始本金1萬 default_qty_value=10000, commission_value=0.04 ) //每次進場1萬，手續費單邊萬分之
4

//start前置設定

strategy.cancel_all() //每次收K都清空委託單
//常用函數
MP = strategy.opentrades.size(strategy.opentrades -1)>0?1:strategy.opentrades.size(strategy.opentrades - 1)<0?-1:0
//end前置設定


//指標計算
Gap = input.float(3, minval=0.01, title="反轉%")
Gap_per = Gap*0.01

//進場條件
MaxUseBars = 1+math.max(10,1)//每個策略要重新設定 LongEntry = bar_index>MaxUseBars and MP<=0 and open[1]-close[1]>Gap_per*close[1] and close>open[1]
ShortEntry = bar_index>MaxUseBars and MP>=0 and close[1]-open[1]>Gap_per*close[1] and close<open[1]

//多單委託
if LongEntry
strategy.entry("LE", strategy.long) //多單進場

//空單委託
if ShortEntry
strategy.entry("SE", strategy.short) //空單進場

//出場條件執行
SL = input.float(5.0,"停損%")
PT = input.float(5.0,"停利%")
EntryPrice = strategy.opentrades.entry_price(strategy.opentrades - 1) //未平倉的進場價
SLPrice = EntryPrice*(1-(MP*SL*0.01))
PTPrice = EntryPrice*(1+(MP*PT*0.01))
if MP>0
strategy.exit("LX", "LE", limit=PTPrice, stop=SLPrice, comment_profit="PT", comment_loss="SL")
if MP<0
strategy.exit("SX", "SE", limit=PTPrice, stop=SLPrice, comment_profit="PT", comment_loss="SL")



//上底色，持有多單底色綠色，持有空單底色紅色
colorBG = strategy.opentrades.size(strategy.opentrades-1)>0 ? color.new(color.green,80) :
strategy.opentrades.size(strategy.opentrades-1)<0 ? color.new(color.red,80)
:
color.new(color.gray,100)
bgcolor(colorBG, force_overlay=true)

//繪圖
plotshape(open-close>Gap_per*close ? true : na,"單根大跌 ",location=location.belowbar, style = shape.diamond)
plotshape(close-open>Gap_per*close ? true : na,"單根大漲 ",location=location.abovebar, style = shape.diamond)


