//@version=5
strategy(title="@課程範例－ORB進化版交易模組（開高走高/開低走低）｜量化通", shorttitle="ORB範例策略｜量化通", //圖表上顯示的短名稱
overlay = false, //true疊圖，false下方單獨視窗 format=format.price, //format.price輸出格式為價格 precision=2, //顯示小數點後兩位
default_qty_type=strategy.cash, initial_capital=10000, //初始本金1萬 default_qty_value=10000, commission_value=0.04 ) //每次進場1萬，手續費單邊萬分之
4

//start前置設定

strategy.cancel_all() //每次收K都清空委託單
//常用函數
MP = strategy.opentrades.size(strategy.opentrades -1)>0?1:strategy.opentrades.size(strategy.opentrades - 1)<0?-1:0
//end前置設定


//指標計算
Len = input.int(5, minval=1, title="開盤後的計算區間")
Gap = input.float(0.1, minval=0.01, title="跳空%數")
Gap_per = Gap*0.01

var TodayBarIndex = 0 //今天開盤後的第n根K棒 if session.isfirstbar //今天開盤第1根K棒
TodayBarIndex := 1 else
TodayBarIndex := TodayBarIndex+1

var TodayOpenType = 0 //紀錄今天的開盤狀況，開高=1，開低=-1，開平=0 if TodayBarIndex==1
if open>close[1]*(1+Gap_per)
TodayOpenType := 1
else if open<close[1]*(1-Gap_per)
TodayOpenType := -1 else
TodayOpenType := 0

HH = ta.highest(high,Len)
LL = ta.lowest(low,Len)
var ORB_High = 0.00
var ORB_Low = 0.00

if TodayBarIndex==Len ORB_High := HH ORB_Low := LL

//進場條件
MaxUseBars = 1+math.max(Len,1)//每個策略要重新設定
LongEntry = bar_index>MaxUseBars and MP<=0 and TodayBarIndex>Len and close>ORB_High[1] //and TodayOpenType==1
ShortEntry = bar_index>MaxUseBars and MP>=0 and TodayBarIndex>Len and close<ORB_Low[1] //and TodayOpenType==-1

//多單委託
if LongEntry
strategy.entry("LE", strategy.long) //多單進場

//空單委託
if ShortEntry
strategy.entry("SE", strategy.short) //空單進場

//出場條件執行
SL = input.float(5.0,"停損%")
PT = input.float(5.0,"停利%")
EntryPrice = strategy.opentrades.entry_price(strategy.opentrades - 1) //未平倉的進場價
SLPrice = EntryPrice*(1-(MP*SL*0.01))
PTPrice = EntryPrice*(1+(MP*PT*0.01))
if MP>0
strategy.exit("LX", "LE", limit=PTPrice, stop=SLPrice, comment_profit="PT", comment_loss="SL")
if MP<0
strategy.exit("SX", "SE", limit=PTPrice, stop=SLPrice, comment_profit="PT", comment_loss="SL")

//上底色，持有多單底色綠色，持有空單底色紅色
colorBG = strategy.opentrades.size(strategy.opentrades-1)>0 ? color.new(color.green,80) :
strategy.opentrades.size(strategy.opentrades-1)<0 ? color.new(color.red,80)
:
color.new(color.gray,100)

bgcolor(colorBG, force_overlay=true)

//繪圖 plot(TodayBarIndex)
plot(ORB_High,"ORB_High",TodayBarIndex>5?color.red:color.new(color.red,100),f orce_overlay = true)
plot(ORB_Low,"ORB_Low",TodayBarIndex>5?color.green:color.new(color.green,100)
,force_overlay = true)


