//@version=5
strategy(title="@課程範例－期現貨價差交易模組（價差發散、價差收斂）｜量化通", shorttitle="期現價差範例策略｜量化通", //圖表上顯示的短名稱
overlay = false, //true疊圖，false下方單獨視窗 format=format.price, //format.price輸出格式為價格 precision=2, //顯示小數點後兩位 initial_capital=500000, //初始本金50萬
commission_type=strategy.commission.cash_per_contract , commission_value=500
) //，手續費單邊500

//start前置設定

strategy.cancel_all() //每次收K都清空委託單
//常用函數
MP = strategy.opentrades.size(strategy.opentrades -1)>0?1:strategy.opentrades.size(strategy.opentrades - 1)<0?-1:0
//end前置設定


//指標計算
Data2 = input.symbol("TWSE:IX0001","Data2商品") //預設Data1為台指期 TXF! 60M , Data2為加權指數
Data2_timeframe = input.timeframe("15","Data2時間週期")
Gap = input.float(50.00,"價差閥值")
Data2_close = request.security(Data2,Data2_timeframe,close)
Spread = close - Data2_close
type = input.string("價差發散", options = ["價差發散","價差收斂"])

//進場條件
MaxUseBars = 1+math.max(10,1)//每個策略要重新設定 var LongEntry = false
var ShortEntry = false

if type=="價差收斂"
LongEntry := bar_index>MaxUseBars and MP<=0 and ta.crossover(Spread,-1*Gap)
ShortEntry := bar_index>MaxUseBars and MP>=0 and ta.crossunder(Spread,Gap)

else if type=="價差發散"
LongEntry := bar_index>MaxUseBars and MP<=0 and ta.crossover(Spread,Gap)
ShortEntry := bar_index>MaxUseBars and MP>=0 and ta.crossunder(Spread,-1*Gap)

//多單委託
if LongEntry
strategy.entry("LE", strategy.long) //多單進場

//空單委託
if ShortEntry
strategy.entry("SE", strategy.short) //空單進場

//上底色，持有多單底色綠色，持有空單底色紅色
colorBG = strategy.opentrades.size(strategy.opentrades-1)>0 ? color.new(color.green,80) :
strategy.opentrades.size(strategy.opentrades-1)<0 ? color.new(color.red,80)
:
color.new(color.gray,100)
bgcolor(colorBG, force_overlay=true)

//繪圖
plot(Data2_close,"Data2",force_overlay = true)
plot(Spread,"Spread")


