//@version=5
strategy(title="@課程範例－相似商品價差交易模組（價差發散、價差收斂）｜量化通", shorttitle="相似價差範例策略｜量化通", //圖表上顯示的短名稱
overlay = false, //true疊圖，false下方單獨視窗 format=format.price, //format.price輸出格式為價格 precision=2, //顯示小數點後兩位
default_qty_type=strategy.cash, initial_capital=10000, //初始本金1萬 default_qty_value=10000, commission_value=0.04 ) //每次進場1萬，手續費單邊萬分之
4

//start前置設定

strategy.cancel_all() //每次收K都清空委託單
//常用函數
MP = strategy.opentrades.size(strategy.opentrades -1)>0?1:strategy.opentrades.size(strategy.opentrades - 1)<0?-1:0
//end前置設定


//指標計算
Data2 = input.symbol("OKX:BTCUSDT","Data2商品") //預設Data1為OKX:ETHUSDT 1小時 Data2_timeframe = input.timeframe("60","Data2時間週期")
Len = input.int(20,"均線長度")
mult = input.float(2.00,"標準差倍數")
Data2_close = request.security(Data2,Data2_timeframe,close)
Spread = Data2_close/close
SpreadMA = ta.sma(Spread,Len)
std = ta.stdev(Spread,Len)
UP = SpreadMA + mult*std
DN = SpreadMA + mult*std*-1

type = input.string("價差發散", options = ["價差發散","價差收斂"])

//進場條件
MaxUseBars = 1+math.max(Len,1)//每個策略要重新設定 var LongEntry = false
var ShortEntry = false

if type=="價差收斂"
LongEntry := bar_index>MaxUseBars and MP<=0 and ta.crossover(Spread,DN)
ShortEntry := bar_index>MaxUseBars and MP>=0 and ta.crossunder(Spread,UP)
else if type=="價差發散"
LongEntry := bar_index>MaxUseBars and MP<=0 and ta.crossover(Spread,UP)
ShortEntry := bar_index>MaxUseBars and MP>=0 and ta.crossunder(Spread,DN)

//多單委託
if LongEntry
strategy.entry("LE", strategy.long) //多單進場

//空單委託
if ShortEntry
strategy.entry("SE", strategy.short) //空單進場

//上底色，持有多單底色綠色，持有空單底色紅色
colorBG = strategy.opentrades.size(strategy.opentrades-1)>0 ? color.new(color.green,80) :
strategy.opentrades.size(strategy.opentrades-1)<0 ? color.new(color.red,80)
:
color.new(color.gray,100)
bgcolor(colorBG, force_overlay=true)

//繪圖
//plot(Data2_close,"Data2",force_overlay = true)
plot(Spread,"Spread")
plot(SpreadMA,color = color.silver)
plot(UP,color = color.red)
plot(DN,color = color.green)


