//@version=5
strategy("@課程範例－指定配對出場法｜量化通", overlay=true, pyramiding=2)

//參數設定
SmallLen = input.int(50, "短均線的長度")
MidLen = input.int(100, "中均線的長度")
BigLen = input.int(200, "長均線的長度")

//計算短均線與長均線
SmallMA = ta.sma(close, SmallLen)
MidMA = ta.sma(close, MidLen)
BigMA = ta.sma(close, BigLen)

longCondition1 = ta.crossover(SmallMA, MidMA)
longCondition2 = ta.crossover(MidMA, BigMA)

//進場條件執行
if longCondition1
strategy.entry("LE1", strategy.long)
else if longCondition2
strategy.entry("LE2", strategy.long)

//出場條件執行
strategy.exit("LX1", "LE1", profit=5000, loss=2000 , comment_profit="LX1_PT", comment_loss="LX1_SL")
strategy.exit("LX2", "LE2", profit=100000, loss=20000, comment_profit="LX2_PT", comment_loss="LX2_SL")

plot(SmallMA,"SmallMA",color.yellow)
plot(MidMA,"MidMA",color.blue)
plot(BigMA,"BigMA",color.orange)

三角加碼法


