//@version=5
strategy("@課程範例－一次出場與分批出場｜量化通", overlay=true, pyramiding=3)

//參數設定
SmallLen = input.int(50, "短均線的長度")
MidLen = input.int(100, "中均線的長度")
BigLen = input.int(200, "長均線的長度")

//計算短均線與長均線
SmallMA = ta.sma(close, SmallLen)
MidMA = ta.sma(close, MidLen)
BigMA = ta.sma(close, BigLen)

longCondition0 = ta.crossover(close, SmallMA)
longCondition1 = ta.crossover(SmallMA, MidMA)
longCondition2 = ta.crossover(MidMA, BigMA)

//進場條件執行
if longCondition0
strategy.entry("LE0", strategy.long, qty=3)
else if longCondition1
strategy.entry("LE1", strategy.long, qty=2)
else if longCondition2
strategy.entry("LE2", strategy.long, qty=1)

//出場條件執行
strategy.exit("LX1", profit=50000, loss=20000) //分批出場 strategy.exit("LX2", profit=100000, loss=30000) //分批出場

if close<SmallMA and SmallMA<MidMA and MidLen<BigMA strategy.close_all() //一次全出

plot(SmallMA,"SmallMA",color.yellow)
plot(MidMA,"MidMA",color.blue)
plot(BigMA,"BigMA",color.orange)


