//@version=5
strategy("@課程範例－萬用出場模組｜量化通", overlay = true, //true疊圖，false下方單獨視窗
format=format.price, //format.price輸出格式為價格 precision=2, //顯示小數點後兩位
default_qty_type=strategy.cash, initial_capital=10000, //初始本金1萬 default_qty_value=10000, commission_value=0.04 ) //每次進場1萬，手續費單邊萬分之
4

//start前置設定

strategy.cancel_all() //每次收K都清空委託單
//常用函數
MP = strategy.opentrades.size(strategy.opentrades -1)>0?1:strategy.opentrades.size(strategy.opentrades - 1)<0?-1:0
//end前置設定


//參數設定
SmallLen = 20//input.int(20, "短均線的長度")
BigLen = 50//input.int(50, "長均線的長度")

//計算短均線與長均線
SmallMA = ta.sma(close, SmallLen)
BigMA = ta.sma(close, BigLen)

MaxUseBars = 1+math.max(SmallLen,BigLen,1)//每個策略要重新設定 longCondition = bar_index>MaxUseBars and MP<=0 and ta.crossover(SmallMA, BigMA)

//進場條件執行
if longCondition
strategy.entry("LE", strategy.long)


//出場條件執行
EntryPrice = strategy.opentrades.entry_price(strategy.opentrades - 1)
BarsSinceEntry = bar_index -strategy.opentrades.entry_bar_index(strategy.opentrades - 1)

//止盈止損
SL = input.float(5, "停損%")
OutKar = input.int(20, "時間出場K棒數")
SLPrice = EntryPrice-(SL*0.01*EntryPrice*MP*1)
PT1Price = EntryPrice+(SL*0.01*EntryPrice*MP*1)
PT2Price = EntryPrice+(SL*0.01*EntryPrice*MP*2)

//多單出場：止損/止盈/時間 var OutPrice = 0.00
if MP>0 and close>=PT2Price
OutPrice := math.max(PT2Price,ta.lowest(low,OutKar/4))
strategy.exit("LX_PT2", stop=OutPrice, comment="LX_止盈2") //多單出場：止盈2
else if MP>0 and close>=PT1Price
OutPrice := math.max(PT1Price,ta.lowest(low,OutKar/2))
strategy.exit("LX_PT1", stop=OutPrice, comment="LX_止盈1") //多單出場：止盈1
else if MP>0 and close<PT1Price and BarsSinceEntry<=OutKar OutPrice := SLPrice
strategy.exit("LX_SL", stop=OutPrice, comment="LX_止損") //多單出場：止損
else if MP>0 and BarsSinceEntry>OutKar and strategy.openprofit>=0 OutPrice := math.max(SLPrice,ta.lowest(low,OutKar))
strategy.exit("LX_Time", stop=OutPrice, comment="LX_時間") //多單出場：時間
else if MP>0 and BarsSinceEntry>OutKar and strategy.openprofit<0 OutPrice := low
strategy.exit("LX_-Time", stop=OutPrice, comment="LX_時間損") //多單出場：時
間
else
OutPrice := na

//上底色，持有多單底色綠色，持有空單底色紅色
colorBG = strategy.opentrades.size(strategy.opentrades-1)>0 ? color.new(color.green,80) :
strategy.opentrades.size(strategy.opentrades-1)<0 ? color.new(color.red,80)
:
color.new(color.gray,100)
bgcolor(colorBG, force_overlay=true)

plot(SmallMA,"SmallMA",color.yellow)
plot(BigMA,"BigMA",color.blue)
plot(OutPrice,"OutPrice",color.red,style = plot.style_linebr)



// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © QuantPass


