//@version=5
strategy("@課程範例－價格高低檔 濾網模組｜量化通", overlay = true, //true疊圖，false下方單獨視窗 format=format.price, //format.price輸出格式為價格 precision=2, //顯示小數點後兩位
default_qty_type=strategy.cash, initial_capital=10000, //初始本金1萬 default_qty_value=10000, commission_value=0.04 ) //每次進場1萬，手續費單邊萬分之
4

//start前置設定

strategy.cancel_all() //每次收K都清空委託單
//常用函數
MP = strategy.opentrades.size(strategy.opentrades -1)>0?1:strategy.opentrades.size(strategy.opentrades - 1)<0?-1:0
//end前置設定


//參數設定
SmallLen = 20//input.int(20, "短均線的長度")
BigLen = 50//input.int(50, "長均線的長度")

//計算短均線與長均線
SmallMA = ta.sma(close, SmallLen)
BigMA = ta.sma(close, BigLen)

MaxUseBars = 1+math.max(SmallLen,BigLen,1)//每個策略要重新設定 longCondition = bar_index>MaxUseBars and MP<=0 and SmallMA>BigMA

//濾網計算
Len = input.int(100, "高低檔判斷長度")
Mid = (ta.highest(high,Len) + ta.lowest(low,Len)) * 0.5 plot(Mid,color = color.silver)

var longFillter = false if close>Mid
longFillter := true else

longFillter := false

//進場條件執行
if longCondition and longFillter strategy.entry("LE", strategy.long)

//出場條件執行
SL = 2.5//input.float(2.5,"停損%")
PT = 10//input.float(10.00,"停利%")
EntryPrice = strategy.opentrades.entry_price(strategy.opentrades - 1) //未平倉的進場價
SLPrice = EntryPrice*(1-(MP*SL*0.01))
PTPrice = EntryPrice*(1+(MP*PT*0.01))
strategy.exit("LX", limit=PTPrice, stop=SLPrice, comment_profit="PT", comment_loss="SL")

plot(SmallMA,"SmallMA",color.yellow,force_overlay = true)
plot(BigMA,"BigMA",color.blue,force_overlay = true)


