//@version=5
strategy(title="@課程範例－優化出場條件與參數調整｜量化通", shorttitle="優化｜量化通", //圖表上顯示的短名稱
overlay = false, //true疊圖，false下方單獨視窗 format=format.price, //format.price輸出格式為價格 precision=2, //顯示小數點後兩位
default_qty_type=strategy.cash, initial_capital=10000, //初始本金1萬 default_qty_value=10000, commission_value=0.04 ) //每次進場1萬，手續費單邊萬分之
4

// OKX:ETHUSDT 4H

//start前置設定

strategy.cancel_all() //每次收K都清空委託單
//常用函數
MP = strategy.opentrades.size(strategy.opentrades -1)>0?1:strategy.opentrades.size(strategy.opentrades - 1)<0?-1:0
//end前置設定


//DMI指標計算
len = input.int(14, minval=1, title="DI長度", group="DMI參數設定")
lensig = input.int(17, minval=1, title="ADX平滑度", group="DMI參數設定")
adx_gap = input.int(20, minval=1, title="ADX門檻", group="DMI參數設定")

[diplus, diminus, adx] = ta.dmi(len, lensig)

//進場條件
MaxUseBars = 1+math.max(len,lensig,1)//每個策略要重新設定
LongEntry = bar_index>MaxUseBars and MP<=0 and diplus>diminus and ta.crossover(adx,adx_gap)
ShortEntry = bar_index>MaxUseBars and MP>=0 and diplus<diminus and ta.crossover(adx,adx_gap)

//多單委託
if LongEntry
strategy.entry("LE", strategy.long) //多單進場

//空單委託
if ShortEntry
strategy.entry("SE", strategy.short) //空單進場


//出場條件執行
SL = input.float(2.5,"停損%")
PT = input.float(10.00,"停利%")
EntryPrice = strategy.opentrades.entry_price(strategy.opentrades - 1) //未平倉的進場價
SLPrice = EntryPrice*(1-(MP*SL*0.01))
PTPrice = EntryPrice*(1+(MP*PT*0.01))
strategy.exit("LX", limit=PTPrice, stop=SLPrice, comment_profit="PT", comment_loss="SL")

//上底色，持有多單底色綠色，持有空單底色紅色
colorBG = strategy.opentrades.size(strategy.opentrades-1)>0 ? color.new(color.green,80) :
strategy.opentrades.size(strategy.opentrades-1)<0 ? color.new(color.red,80)
:
color.new(color.gray,100)
bgcolor(colorBG, force_overlay=true)

//定義ADX線條顏色
adxColor = adx>=adx_gap ? color.yellow : color.silver
//繪圖
plot(adx, color=adxColor, title="ADX")
plot(diplus, color=color.red, title="+DI")
plot(diminus, color=color.green, title="-DI")
hline(adx_gap, "ADX門檻", color=color.new(color.gray, 50))


