//@version=5
strategy(title="@課程範例－高效波段策略｜量化通", shorttitle="高效策略｜量化通", //圖表上顯示的短名稱 overlay = false, //true疊圖，false下方單獨視窗 format=format.price, //format.price輸出格式為價格 precision=2, //顯示小數點後兩位
default_qty_type=strategy.cash, initial_capital=10000, //初始本金1萬 default_qty_value=10000, commission_value=0.04 ) //每次進場1萬，手續費單邊萬分之
4

//start前置設定

strategy.cancel_all() //每次收K都清空委託單
//常用函數
//常用函數
MP = strategy.opentrades.size(strategy.opentrades -1)>0?1:strategy.opentrades.size(strategy.opentrades - 1)<0?-1:0 EntryPrice = strategy.opentrades.entry_price(strategy.opentrades - 1)
BarsSinceEntry = bar_index -strategy.opentrades.entry_bar_index(strategy.opentrades - 1)
//end前置設定


//指標計算
Len = input.int(20, "計算長度")
Eff = input.float(0.5, "效率判斷")
SingleDistance = math.abs(close-close[1])
TotalDistance = math.sum(SingleDistance,Len-1)
StraightDistance = close-close[Len]
Efficiency = StraightDistance / TotalDistance plot(Efficiency)

//進場條件
MaxUseBars = 1+math.max(Len,1)//每個策略要重新設定
LongEntry = bar_index>MaxUseBars and MP<=0 and ta.crossover(Efficiency,Eff)
ShortEntry = bar_index>MaxUseBars and MP>=0 and ta.crossunder(Efficiency,-Eff)

//多單委託
if LongEntry
strategy.entry("LE", strategy.long)

//空單委託
if ShortEntry
strategy.entry("SE", strategy.short)

//出場條件執行
if MP>0 and ta.crossunder(Efficiency,0)
strategy.exit("LX", stop=low)
if MP<0 and ta.crossover(Efficiency,0)
strategy.exit("SX", stop=high)

//上底色，持有多單底色綠色，持有空單底色紅色
colorBG = strategy.opentrades.size(strategy.opentrades-1)>0 ? color.new(color.green,80) :
strategy.opentrades.size(strategy.opentrades-1)<0 ? color.new(color.red,80)
:
color.new(color.gray,100)
bgcolor(colorBG, force_overlay=true)


