//@version=5
strategy(title="@課程範例－價差策略｜量化通", shorttitle="價差策略｜量化通", //圖表上顯示的短名稱 overlay = false, //true疊圖，false下方單獨視窗 format=format.price, //format.price輸出格式為價格 precision=2, //顯示小數點後兩位
default_qty_type=strategy.cash, initial_capital=10000, //初始本金1萬 default_qty_value=10000, commission_value=0.04 ) //每次進場1萬，手續費單邊萬分之
4

//start前置設定

strategy.cancel_all() //每次收K都清空委託單
//常用函數
//常用函數
MP = strategy.opentrades.size(strategy.opentrades -1)>0?1:strategy.opentrades.size(strategy.opentrades - 1)<0?-1:0 EntryPrice = strategy.opentrades.entry_price(strategy.opentrades - 1)
BarsSinceEntry = bar_index -strategy.opentrades.entry_bar_index(strategy.opentrades - 1)
//end前置設定


//指標計算
Data2 = input.symbol("OKX:BTCUSDT","Data2商品") //預設Data1為OKX:ETHUSDT Data2_timeframe = input.timeframe("60","Data2時間週期") //兩個商品的時間週期設定要相同
Len = input.int(20,"均線長度")
mult1 = input.float(1.50,"順勢標準差倍數")
mult2 = input.float(3.00,"逆勢標準差倍數")

Data2_close = request.security(Data2,Data2_timeframe,close)
Spread = close/Data2_close //若是期貨現貨價差要改成相減 SpreadMA = ta.sma(Spread,Len)

std = ta.stdev(Spread,Len)
UP1 = SpreadMA + mult1*std DN1 = SpreadMA + mult1*std*-1

UP2 = SpreadMA + mult2*std DN2 = SpreadMA + mult2*std*-1

//進場條件
MaxUseBars = 1+math.max(Len,1)//每個策略要重新設定 LongEntry = bar_index>MaxUseBars and MP<=0 ShortEntry = bar_index>MaxUseBars and MP>=0

//多單委託
if LongEntry and ta.crossover(Spread,UP1)
strategy.entry("LE_順勢", strategy.long) //多單進場
if LongEntry and ta.crossover(Spread,DN2)
strategy.entry("LE_逆勢", strategy.long) //多單進場

//空單委託
if ShortEntry and ta.crossunder(Spread,DN1)
strategy.entry("SE_順勢", strategy.short) //空單進場
if ShortEntry and ta.crossunder(Spread,UP2)
strategy.entry("SE_順勢", strategy.short) //空單進場

//出場條件執行
SL = input.float(5.00,"停損%")
PT = input.float(10.00,"停利%")
SLPrice = EntryPrice*(1-(MP*SL*0.01))
PTPrice = EntryPrice*(1+(MP*PT*0.01))
if MP>0
strategy.exit("LX", limit=PTPrice, stop=SLPrice)
if MP<0
strategy.exit("SX", limit=PTPrice, stop=SLPrice)
if MP>0 and Spread<SpreadMA
strategy.exit("LX_MA", stop=low)
if MP<0 and Spread>SpreadMA
strategy.exit("SX_MA", stop=high)

//上底色，持有多單底色綠色，持有空單底色紅色
colorBG = strategy.opentrades.size(strategy.opentrades-1)>0 ? color.new(color.green,80) :
strategy.opentrades.size(strategy.opentrades-1)<0 ? color.new(color.red,80)
:
color.new(color.gray,100)
bgcolor(colorBG, force_overlay=true)

//繪圖
//plot(Data2_close,"Data2",force_overlay = true)
plot(Spread,"Spread",color = color.silver)

plot(SpreadMA)
plot(UP1,color = color.red)
plot(DN1,color = color.green)


